services:
  postgres:
    container_name: postgres_container
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: ${DB_USER?MISSING VARIABLE}
      POSTGRES_PASSWORD: ${DB_PASS?MISSING VARIABLE}
      POSTGRES_DB: ${DB_NAME?MISSING VARIABLE}
      PGDATA: /data/postgres
    volumes:
       - /postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge