version: '3.1'
services:
  mysql:
    image: circleci/mysql:5.7
    container_name: mysql.dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "security"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    links:
      - mysql
    ports:
      - 18080:8080
      
volumes:
  mysql: