global:
  resolve_timeout: 5m

route:
#  receiver: 'slack-notifications'
  receiver: 'null-receiver'
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

#receivers:
#  - name: 'slack-notifications'
#    slack_configs:
#      - api_url: 'https://hooks.slack.com/services/T000/B000/XXXXX'
#        channel: '#alerts'
#        send_resolved: true

receivers:
  - name: 'null-receiver'