global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: 'sc-platform'
    metrics_path: '/platform-info/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'postgres-exporter'
#    metrics_path: '/metrics'
    honor_labels: true
#    scrape_interval: 300s
#    scrape_timeout: 60s
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
        labels:
          service_name: 'postgres-exporter'
  - job_name: 'mongodb-exporter'
    metrics_path: '/metrics'
    honor_labels: true
    #    scrape_interval: 300s
    #    scrape_timeout: 60s
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'mongodb-exporter:9216' ]
        labels:
          service_name: 'mongodb-exporter'
#  - job_name: 'mongodb-query-exporter'
#    metrics_path: '/metrics'
#    honor_labels: true
#    #    scrape_interval: 300s
#    #    scrape_timeout: 60s
#    scrape_interval: 15s
#    scrape_timeout: 10s
#    static_configs:
#      - targets: [ 'mongodb-query-exporter:9412' ]
#        labels:
#          service_name: 'mongodb-query-exporter'
  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    honor_labels: true
    #    scrape_interval: 300s
    #    scrape_timeout: 60s
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'cadvisor:8080' ]
        labels:
          service_name: 'cadvisor'