version: '3'
services:
  openproject:
    image: openproject/community:latest
    ports:
      - 8080:80
    volumes:
      - /op-data:/var/openproject/static:rw
    environment:
      - DATABASE_URL=postgres://weesy:weesy9866892726@postgres:5432/openproject
      - SECRET_KEY_BASE=secret      
      - EMAIL_DELIVERY_METHOD="smtp"
      - SMTP_ADDRESS="smtp.mailgun.org"
      - SMTP_PORT="587"
      - SMTP_DOMAIN="weesy.com.br"
      - SMTP_AUTHENTICATION="plain"
      - SMTP_USER_NAME="postmaster@myDomain.com"
      - SMTP_PASSWORD="MyPassword"
      - SMTP_ENABLE_STARTTLS_AUTO="true"
    depends_on:
      - postgres
    networks:
      - default
      
  postgres:
    image: postgres:9.6-alpine
    networks:
     - default
    volumes:
      - /db-data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=openproject
      - POSTGRES_USER=weesy
      - POSTGRES_PASSWORD=weesy9866892726
    ports:
     - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
