version: '2.1'

services:
  oracle-xe:
    image: daggerok/oracle
    shm_size: 1g
    environment:
      ORACLE_PWD: password
      APEX_PORT: 8080
    ports:
    - '1521:1521'
    - '8080:8080'
    networks: [backing-services]
    healthcheck:
      test: curl -uSYSTEM:$$ORACLE_PWD -v http://127.0.0.1:$$APEX_PORT//apex/
      timeout: 2s
      retries: 100

networks:
  backing-services:
    driver: bridge
