version: '3.1'
services:
 db:
  image: daggerok/oracle:11.2.0.2-xe
  ports:
    - 1521:1521
    - 8085:8080
  shm_size: 1g
  volumes:
    - ./data:/u01/app/oracle/oradata
  environment:
    - ORACLE_PWD=zagreb_2017
  restart: unless-stopped