version: "3.4"

services:
  traefik:
    image: traefik:v1.7.34
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/config/traefik.toml:/traefik.toml
      - ./traefik/certs/:/certs/
      - /var/run/docker.sock:/var/run/docker.sock